### PR TITLE
(GH-769) API - Resolve Merged Assemblies

### LINKED ISSUE #769: Issue when attempting to execute run command through API
### What You Are Seeing?
An exception when running any sort of `run()` command.

### What is Expected?
Executing a `run` command should work fine.

### How Did You Get This To Happen? (Steps to Reproduce)
With the latest chocolatey.lib `0.9.10-beta-20160531` trying and run: 
```            
           var choco = Lets.GetChocolatey();
            choco.Set(
                config =>
                {
                    config.CommandName = "source";
                    config.SourceCommand.Command = SourceCommandType.add;
                    config.SourceCommand.Name = "test";
                    config.Sources = "c:\\packages\\";
                    config.AllowUnofficialBuild = true;
                });

            choco.Run();
```

### Output Log
```
The type initializer for 'System.Reactive.Linq.Observable' threw an exception.
   at System.Reactive.Linq.Observable.OfType[TResult](IObservable`1 source)
   at chocolatey.infrastructure.services.EventSubscriptionManagerService.subscribe[Event](Action`1 handleEvent, Action`1 handleError, Func`2 filter)
   at chocolatey.infrastructure.app.tasks.RemovePendingPackagesTask.initialize()
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.GetChocolatey.Run()
   at ChocolateyGui.Utilities.Extensions.ChocolateyExtensions.<>c__DisplayClass0_0.<RunAsync>b__0() in C:\Source\FOSS\ChocolateyGUI\Source\ChocolateyGui\Utilities\Extensions\ChocolateyExtensions.cs:line 19
   at System.Threading.Tasks.Task.Execute()
```

```
{"Could not load file or assembly 'System.Reactive.PlatformServices, Version=0.9.10.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.Reactive.PlatformServices, Version=0.9.10.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb"}
```

### PR DESCRIPTION
**Pull request by ferventcoder**
When using the API, it should resolve merged assemblies but it may
not if there is an assembly handler registered. Before loading up
code that resolves external assemblies, register an AssemblyResolve
handler with the purpose of determining if the assembly has
Chocolatey's Public Key token or not. If it does, use Chocolatey's
merged assembly instead of the conflicting assembly.

Closes #769

### CODE REVIEW

**Comment by ferventcoder** [comment]
@RichiCoder1 can you take a look at this? I'm not sure if you can build it for testing though, since the keys will be different.

**Comment by RichiCoder1** [comment]
Does this also include changes that cause all merged assemblies to have choco's public key? The issue was that choco was trying to activate a type that was in "System.Reactive.PlatformServices" with it's own public key and was picking up mine instead of the one in choco.

File: src/chocolatey/GetChocolatey.cs [hunk 1]
```diff
@@ -41,8 +41,27 @@ public static class Lets
...
+        private static ResolveEventHandler _handler = null;
+
+        private static void add_assembly_resolver()
+        {
+            _handler = (sender, args) =>
+            {
+                var requestedAssembly = new AssemblyName(args.Name);
+                if (requestedAssembly.get_public_key_token().is_equal_to(ApplicationParameters.OfficialChocolateyPublicKey))
+                {
+                     return typeof(Lets).Assembly;
```
Comment (ferventcoder) [inline src/chocolatey/GetChocolatey.cs]: @RichiCoder1 It's checking the public key token of the requested assembly - meaning that when choco is pulling an item is has merged in, the keys will match. So it will use the internal instead of an external conflicting Assembly. Does this answer your question?
