### PR TITLE
(#2407) Update licensed assembly not found warning

### LINKED ISSUE #2407: License warning message needs to be updated
### What You Are Seeing?

When adding a license to a Chocolatey installation, the following message is emitted when `choco` is invoked:

```code
Error when attempting to load chocolatey licensed assembly. Ensure
 that chocolatey.licensed.dll exists at
 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.
 The error message itself may be helpful:
 Could not find file 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.
 Install the Chocolatey Licensed Extension package with
 `choco install chocolatey.extension` to remove this license warning.
 TRIALS: If you have a trial license, you cannot use the above command
 as is and be successful. You need to download nupkgs from the links in
 the trial email as your license will not be registered on the licensed
 repository. Please reference
 https://docs.chocolatey.org/en-us/licensed-extension/setup#how-do-i-install-the-trial-edition
 for specific instructions.
```

### What is Expected?

The information around trials not being able to use the licensed repository is outdated and needs to be removed. I would also suggest that some parts of the error are redundant and/or unhelpful. Should we even have an error here, or just a warning? The wording here indicates it's meant to be a warning more than anything.

Maybe we could word it something like this?

```code
A valid Chocolatey license was found, but the chocolatey licensed assembly could not be loaded:
  Could not find file 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.
Ensure that the chocolatey.licensed.dll exists at the following path:
 'C:\ProgramData\chocolatey\extensions\chocolatey\chocolatey.licensed.dll'.

To resolve this, install the Chocolatey Licensed Extension package with:
 `choco install chocolatey.extension`
```

Potentially we could have Chocolatey install the extension automatically if it detects it's licensed, but that would be a larger discussion. At the very least we can update the message for now to avoid confusing folks. The documentation linked in the original message has already been updated.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Have Chocolatey installed, without `chocolatey.extension`
2. Add a valid `chocolatey.license.xml` file to the `$env:ChocolateyInstall\license` directory
3. Run `choco` in a command line / powershell

### Output Log

Not really relevant here, I don't think.

### PR DESCRIPTION
**Pull request by vexx32**
## Description Of Changes

Removed mention of trials not being able to install the extension in the normal way (this is no longer the case), and clarified the error and warning a little more succinctly.

## Motivation and Context

The error message is outdated and gives trial customers the wrong information, as well as linking to docs that now contradict the error message.

## Testing

1. Build and run/install the `choco` from the repo
2. Add a valid `chocolatey.license.xml` without installing `chocolatey.extension`
3. Run `choco list -lo` (or any other `choco` command)
4. Note the error message and warning emitted when the chocolatey.licensed.dll cannot be found

## Change Types Made

* [x] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #2407

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

File: src/chocolatey/infrastructure/licensing/License.cs [hunk 1]
```diff
@@ -50,22 +50,15 @@ public static ChocolateyLicense validate_license()
...
- TRIALS: If you have a trial license, you cannot use the above command
- as is and be successful. You need to download nupkgs from the links in
- the trial email as your license will not be registered on the licensed
- repository. Please reference
- https://docs.chocolatey.org/en-us/licensed-extension/setup#how-do-i-install-the-trial-edition
- for specific instructions.");
+                        @"A valid Chocolatey license was found, but the chocolatey.licensed.dll assembly could not be loaded:
+  {0}
+Ensure that the chocolatey.licensed.dll exists at the following path:
+ '{1}'".format_with(ex.Message, ApplicationParameters.LicensedAssemblyLocation));
```
Comment (pauby) [inline src/chocolatey/infrastructure/licensing/License.cs:56]: We're not passing the error message in ` ex.Message` through here? Is there a reason for this?

Comment (vexx32) [reply src/chocolatey/infrastructure/licensing/License.cs:56]: I'm not sure what you mean? The `format_with()` will insert the value of `ex.Message` into the format string, which is then logged as an error.

Comment (pauby) [reply src/chocolatey/infrastructure/licensing/License.cs:56]: DOH! I genuinely didn't see the `ex.Message` in yours. It's right at the beginning 😄

**Review by pauby — APPROVED** [review]

**Review by gep13 — APPROVED** [review]
LGTM!
