### PR TITLE
(#886, 2693) Update packages.config install logging and add back resolve or load method for Assembly Resolution

### LINKED ISSUE #886: Packages.config should include all options (including ignorechecksums)
### What You Are Seeing?

cinst on command-line using a .config file disregards ignorechecksum for specific packages.
### What is Expected?

an entry in a .config file that includes `ignorechecksums="true" or another of the aliases from https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches should honor the ignorechecksums directive and allow, for that specific package,an installer that fails the checksums verification to be installed.
### How Did You Get This To Happen? (Steps to Reproduce)

ran `cinst rt.config -y` using the attached rt.config.txt file.
[rt.config.txt](https://github.com/chocolatey/choco/files/394245/rt.config.txt)
### Output Log

chocolatey.log: https://gist.github.com/cori/01ff60e1638b75f38a25cbe41e7a0a16
choco.summary.log: https://gist.github.com/cori/b51791c5e22e19180d1e31e0eee717f1

### LINKED ISSUE #2693: Enhance registrations to be able to load officially signed extensions
Currently when/if we want to update existing commands or add new commands in other projects using Chocolatey CLI we need to replace all commands by re-registering the commands and add any new/updated commands to the same list that we are re-registering.

This work item is to make this process more streamlined/easier to do, so we only need to adde/replace the commands we are interested in.

The exact scope of work is not known at this time, but this issue is a placeholder to do this work.

### PR DESCRIPTION
**Pull request by corbob**
## Description Of Changes

Update the debugging output for the install from packages.config file to clearly delineate the start and end of the configuration output.

Add back the original definition of resolve_or_load_assembly to AssemblyResolution.

## Motivation and Context

The output of the Configuration when Licensed Extension is installed is different from when just Open Source is in play. As such, the tests for the new functionality was failing. This updates the output to enable us to better test the command.

Chocolatey GUI fails to load with the update to `resolve_or_load_assembly`, so added back the original definition.

## Testing

1. Downloaded build artifacts from build server and installed on VM
2. Installed Chocolatey GUI
3. Launched Chocolatey GUI
4. Confirmed it launched successfully
5. Installed Licensed Extension
6. Ensured the Pester tests for InstallCommand completed successfully.

## Change Types Made

* [x] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #886
Fixes #2693 

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [x] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

File: src/chocolatey/infrastructure/registration/AssemblyResolution.cs [hunk 1]
```diff
@@ -31,6 +31,18 @@ public class AssemblyResolution
...
 
+        /// <summary>
+        /// Resolves or loads an assembly. If an assembly is already loaded, no need to reload it.
+        /// </summary>
+        /// <param name="assemblySimpleName">Simple Name of the assembly, such as "chocolatey"</param>
+        /// <param name="publicKeyToken">The public key token.</param>
+        /// <param name="assemblyFileLocation">The assembly file location. Typically the path to the DLL on disk.</param>
+        /// <returns>An assembly</returns>
+        /// <exception cref="Exception">Unable to enter synchronized code to determine assembly loading</exception>
+        public static IAssembly resolve_or_load_assembly(string assemblySimpleName, string publicKeyToken, string assemblyFileLocation) {
```
Comment (gep13) [inline src/chocolatey/infrastructure/registration/AssemblyResolution.cs:42]: If the intention is to remove this, should we not mark it as obsolete?

Comment (AdmiringWorm) [reply src/chocolatey/infrastructure/registration/AssemblyResolution.cs:42]: From what Cory told be on Slack, it is being used by Chocolatey GUI, and since it is just an overload of the other method there isn't really a need to deprecate it.

Doesn't hurt to just keep it around.

File: tests/chocolatey-tests/commands/choco-install.Tests.ps1 [hunk 2]
```diff
@@ -247,9 +247,11 @@ Describe "choco install" -Tag Chocolatey, InstallCommand {
                 $Output = Invoke-Choco install $env:CHOCOLATEY_TEST_PACKAGES_PATH\alloptions.packages.config --confirm --verbose --debug
 
                 # This is based on two observations: The addition explicitly outputs that it's the Package Configuration.
-                # The configuration output is also about 80 lines.
-                $StartofPackageConfiguration = [array]::IndexOf($Output.Lines, "Package Configuration: CommandName='install'|")
-                $PackageConfigurationOutput = $Output.Lines[$StartofPackageConfiguration..($StartofPackageConfiguration+80)] -join [Environment]::NewLine
+                # The configuration output is about 80 lines.
+                $StartOfPackageConfiguration = [array]::IndexOf($Output.Lines, "Package Configuration Start:")
+                $EndOfPackageConfiguration = [array]::IndexOf($Output.Lines, "Package Configuration End")
```
Comment (AdmiringWorm) [inline tests/chocolatey-tests/commands/choco-install.Tests.ps1:252]: Not so sure about just updating the logic here just to adhere to tests.

Not pushing back against it, just mentioning it feels a bit wrong when that is used as the excuse for the change.

Comment (corbob) [reply tests/chocolatey-tests/commands/choco-install.Tests.ps1:252]: Yeah, I'd tend to agree it's not great. However, the alternatives that I could think of would make the tests quite fragile and mean that any configuration change (either adding configuration options, or changing the default settings) could break the tests.

File: src/chocolatey/infrastructure/registration/AssemblyResolution.cs (hunk 1 above)
Comment (corbob) [reply src/chocolatey/infrastructure/registration/AssemblyResolution.cs:42]: I'm good with marking this as obsolete if we want. A benefit of not obsoleting it is that anyone currently using Chocolatey.Lib doesn't need to do anything since this just calls the new method with the default value of that method anyways.

**Review by AdmiringWorm — APPROVED** [review]
LGTM, but need to leave it up to @gep13 to decide whether we should mark the overload as obsolete or not (as already mentioned, I don't mind either way).

**Comment by gep13** [comment]
If everyone is happy, then I would say let's not add the `Obsolete` attribute, and leave the overload for the method in place.

**Comment by gep13** [comment]
@corbob thanks for getting this fixed up!
